# Generated by Django 6.0 on 2025-12-19 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mahalla",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_mahallas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Neighborhood admin",
            ),
        ),
        migrations.AddField(
            model_name="mahalla",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mahallas",
                to="regions.district",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="regions.region",
                verbose_name="Region",
            ),
        ),
    ]
