# Generated by Django 6.0 on 2025-12-19 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="House number"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "House",
                "verbose_name_plural": "Houses",
                "ordering": ["-created_at"],
            },
        ),
    ]
