# Generated by Django 6.0 on 2025-12-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("houses", "0001_initial"),
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="mahalla",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="houses",
                to="regions.mahalla",
                verbose_name="Neighborhood",
            ),
        ),
    ]
