# Generated by Django 6.0 on 2025-12-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="house_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="House number"
            ),
        ),
    ]
