# Generated by Django 6.0 on 2026-01-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_alter_house_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='created_by_agent',
            field=models.BooleanField(default=False, verbose_name='Created by agent'),
        ),
    ]
