# Generated by Django 6.0 on 2025-12-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="scanned_qr_code",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="Scanned QR Code UUID",
            ),
        ),
    ]
