# Generated by Django 6.0 on 2025-12-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_scanned_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('government', 'Government Officer'), ('mahalla_admin', 'Neighborhood Admin'), ('user', 'User')], default='user', max_length=20, verbose_name='Role'),
        ),
    ]
