# Generated by Django 6.0 on 2025-12-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_address_remove_user_passport_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("gov", "Government"),
                    ("leader", "Leader"),
                    ("client", "Client"),
                    ("agent", "Agent"),
                ],
                default="client",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
