# Generated by Django 6.0 on 2025-12-28 12:03

from django.db import migrations


def migrate_roles_forward(apps, schema_editor):
    """Migrate old role names to new role names"""
    User = apps.get_model("users", "User")

    # Update roles in bulk
    role_mapping = {
        "super_admin": "admin",
        "government": "gov",
        "mahalla_admin": "leader",
        "user": "client",
    }

    for old_role, new_role in role_mapping.items():
        User.objects.filter(role=old_role).update(role=new_role)


def migrate_roles_backward(apps, schema_editor):
    """Reverse migration - convert new role names back to old ones"""
    User = apps.get_model("users", "User")

    # Reverse mapping
    role_mapping = {
        "admin": "super_admin",
        "gov": "government",
        "leader": "mahalla_admin",
        "client": "user",
    }

    for new_role, old_role in role_mapping.items():
        User.objects.filter(role=new_role).update(role=old_role)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_update_role_choices"),
    ]

    operations = [
        migrations.RunPython(migrate_roles_forward, migrate_roles_backward),
    ]
