# Generated by Django 6.0 on 2026-01-03 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
        ("users", "0005_migrate_old_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mahalla",
            field=models.ForeignKey(
                blank=True,
                help_text="Mahalla for leader role",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leaders",
                to="regions.mahalla",
                verbose_name="Mahalla",
            ),
        ),
    ]
