# Generated by Django 6.0 on 2026-01-09 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_mahalla'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='Telefon raqami')),
                ('message', models.TextField(verbose_name='SMS matni')),
                ('sms_type', models.CharField(choices=[('verification', 'Tasdiqlash kodi'), ('registration', "Ro'yxatdan o'tish"), ('qr_scan', 'QR kod skaner'), ('notification', 'Bildirishnoma')], db_index=True, default='notification', max_length=20, verbose_name='SMS turi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xato'), ('delivered', 'Yetkazildi')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xato xabari')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqti')),
                ('eskiz_response', models.JSONField(blank=True, null=True, verbose_name='Eskiz API javobi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='users_smslo_created_a12545_idx'), models.Index(fields=['phone', '-created_at'], name='users_smslo_phone_4435e1_idx'), models.Index(fields=['sms_type', '-created_at'], name='users_smslo_sms_typ_f433c6_idx')],
            },
        ),
    ]
