# Generated by Django 6.0 on 2025-12-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='Scanned at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrcodes.qrcode', verbose_name='QR Code')),
            ],
            options={
                'verbose_name': 'Scan Log',
                'verbose_name_plural': 'Scan Logs',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
