# Generated by Django 6.0 on 2025-12-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanlog",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
