# Generated by Django 6.0 on 2025-12-16 11:55

import apps.qrcodes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.CharField(default=apps.qrcodes.models.generate_16_char_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('object_type', models.CharField(choices=[('house', 'Uy'), ('car', 'Mashina'), ('other', 'Boshqa')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
