# Generated by Django 6.0 on 2025-12-17 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=16, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "house",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_code",
                        to="houses.house",
                    ),
                ),
            ],
        ),
    ]
