# Generated by Django 6.0 on 2025-12-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR code image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='houses.house', verbose_name='House')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
