# Generated by Django 6.0 on 2025-12-19 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivered at'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_qrcodes', to=settings.AUTH_USER_MODEL, verbose_name='Delivered by'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='Is delivered to house owner'),
        ),
    ]
