# Generated by Django 6.0 on 2025-12-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodes", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qrcode",
            options={
                "ordering": ["id"],
                "verbose_name": "QR Code",
                "verbose_name_plural": "QR Codes",
            },
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
