# Generated by Django 6.0 on 2025-12-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodes", "0002_qrcode_delivered_at_qrcode_delivered_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="numeric_id",
            field=models.IntegerField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="Numeric ID",
            ),
        ),
    ]
