# Generated by Django 6.0 on 2025-12-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0003_alter_qrcode_options_alter_qrcode_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='delivered_by',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='is_delivered',
        ),
    ]
