# Generated by Django 6.0 on 2026-01-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_alter_house_id'),
        ('qrcodes', '0006_cleanup_orphaned_house_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='houses.house', verbose_name='House'),
        ),
    ]
