# Generated by Django 6.0 on 2026-01-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0007_change_house_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_scanned',
            field=models.BooleanField(default=False, verbose_name='Is Scanned'),
        ),
    ]
